version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/core:/etc/nginx/conf.d
      - ./nginx/www:/var/www/
      - ./nginx/logs:/var/log/nginx/
      - ./nginx/html:/usr/share/nginx/html/
      - ./nginx/certs:/etc/nginx/certs
    links:
      - php
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "127.0.0.1:3309:3306"
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=dev01
      - MYSQL_DATABASE=magento
      - MYSQL_USER=mag
      - MYSQL_PASSWORD=dev01
    volumes:
      - ./mysql:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    container_name: mailhog
    restart: always

  php:
    build: ./php
    container_name: php-fpm
    restart: always
    volumes:
      - ./nginx/www:/var/www
      - ./home/user/.ssh:/root/.ssh
    links:
      - mysql

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports:
      - "9999:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --no-auth -H unix:///var/run/docker.sock

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - "127.0.0.1:8080:8080"

  elasticsearch:
   image: elasticsearch:7.8.1
   container_name: elasticsearch
   restart: always
   ports:
     - "127.0.0.1:9200:9200"
     - "127.0.0.1:9300:9300"
   environment:
     - "bootstrap.memory_lock=true"
     - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
     - "discovery.type=single-node"
   ulimits:
      memlock:
        soft: -1
        hard: -1
